### ISSUE TITLE
API обновился, когда планируете догнать?

### ISSUE THREAD

**Issue by shevtsov-max** [yandex-market/marketplace-php-partner#11]
В API появились "[Отчет по заказам](https://yandex.ru/dev/market/partner-marketplace/doc/dg/reference/post-campaigns-id-stats-orders-docpage/)" и "[Отчет по товарам](https://yandex.ru/dev/market/partner-marketplace/doc/dg/reference/post-campaigns-id-stats-skus-docpage/)", когда планируете релиз с поддержкой данных запросов?

**Comment by matiosfree** [comment]
Аналогичный вопрос. Видимо придется пока реализовывать саму :)

**Comment by VitaliaSmaglenko** [comment]
Новые запросы появились с версией [v3.2.0](https://github.com/yandex-market/marketplace-php-partner/tree/3.2.0)
